language: node_js
node_js:
- '10'
before_install:
  - pip install awscli --upgrade --user

install:
  - npm i
script:
  - npm run build
  - ls -la
  - aws s3 cp ./dist s3://www.thejinjr.com/ --recursive --acl public-read